import type { DeviceKind } from "./art";

/** Demo catalogue for development. Prices are in JOD (major units). */

type L = { en: string; ar: string };
const L = (en: string, ar: string): L => ({ en, ar });

export const ATTRIBUTE_GROUPS = [
  { key: "display", name: L("Display", "الشاشة"), position: 1 },
  { key: "performance", name: L("Performance", "الأداء"), position: 2 },
  { key: "camera", name: L("Camera", "الكاميرا"), position: 3 },
  { key: "battery", name: L("Battery & charging", "البطارية والشحن"), position: 4 },
  { key: "connectivity", name: L("Connectivity", "الاتصال"), position: 5 },
  { key: "physical", name: L("Design", "التصميم"), position: 6 },
  { key: "general", name: L("General", "عام"), position: 7 },
];

type AttrDef = {
  key: string;
  name: L;
  type: "SELECT" | "MULTISELECT" | "COLOR" | "TEXT" | "NUMBER" | "BOOLEAN";
  group: string;
  filterable?: boolean;
  variant?: boolean;
  unit?: string;
  values?: { slug: string; label: L; hex?: string }[];
};

const sel = (slug: string, en: string, ar = en) => ({ slug, label: L(en, ar) });
const col = (slug: string, en: string, ar: string, hex: string) => ({ slug, label: L(en, ar), hex });

export const COLORS = {
  black: col("black", "Black", "أسود", "#1c1c1e"),
  white: col("white", "White", "أبيض", "#f2f2f4"),
  silver: col("silver", "Silver", "فضي", "#d9dadc"),
  "cosmic-orange": col("cosmic-orange", "Cosmic Orange", "برتقالي كوني", "#e46a2e"),
  "deep-blue": col("deep-blue", "Deep Blue", "أزرق غامق", "#2c3e5c"),
  lavender: col("lavender", "Lavender", "خزامى", "#c9b8e6"),
  sage: col("sage", "Sage", "مريمية", "#b7c4a5"),
  "mist-blue": col("mist-blue", "Mist Blue", "أزرق ضبابي", "#a9c3d9"),
  "sky-blue": col("sky-blue", "Sky Blue", "أزرق سماوي", "#9fc7e8"),
  "titanium-black": col("titanium-black", "Titanium Black", "أسود تيتانيوم", "#2b2b2d"),
  "titanium-silverblue": col("titanium-silverblue", "Titanium Silverblue", "فضي مزرق تيتانيوم", "#9fb2c8"),
  "titanium-gray": col("titanium-gray", "Titanium Gray", "رمادي تيتانيوم", "#7d7f82"),
  navy: col("navy", "Navy", "كحلي", "#23304a"),
  "icy-blue": col("icy-blue", "Icy Blue", "أزرق جليدي", "#bcd6ea"),
  mint: col("mint", "Mint", "نعناعي", "#bfe3cf"),
  obsidian: col("obsidian", "Obsidian", "أوبسيديان", "#202124"),
  porcelain: col("porcelain", "Porcelain", "بورسلين", "#ece7df"),
  moonstone: col("moonstone", "Moonstone", "حجر القمر", "#8ea3b8"),
  green: col("green", "Green", "أخضر", "#3e6b55"),
  gold: col("gold", "Gold", "ذهبي", "#d8c08f"),
  purple: col("purple", "Purple", "بنفسجي", "#6d4fa3"),
  pink: col("pink", "Pink", "وردي", "#f1b9c8"),
  clear: col("clear", "Clear", "شفاف", "#e8eef3"),
  starlight: col("starlight", "Starlight", "ضوء النجوم", "#efe6d6"),
  "jet-black": col("jet-black", "Jet Black", "أسود فاحم", "#0e0e10"),
  "rose-gold": col("rose-gold", "Rose Gold", "ذهبي وردي", "#e7c2b4"),
};

export const ATTRIBUTES: AttrDef[] = [
  { key: "color", name: L("Color", "اللون"), type: "COLOR", group: "physical", filterable: true, variant: true, values: Object.values(COLORS) },
  {
    key: "storage",
    name: L("Storage", "السعة التخزينية"),
    type: "SELECT",
    group: "performance",
    filterable: true,
    variant: true,
    values: [sel("64gb", "64GB"), sel("128gb", "128GB"), sel("256gb", "256GB"), sel("512gb", "512GB"), sel("1tb", "1TB"), sel("2tb", "2TB")],
  },
  {
    key: "ram",
    name: L("RAM", "الذاكرة العشوائية"),
    type: "SELECT",
    group: "performance",
    filterable: true,
    variant: true,
    values: [sel("6gb", "6GB"), sel("8gb", "8GB"), sel("12gb", "12GB"), sel("16gb", "16GB"), sel("24gb", "24GB")],
  },
  {
    key: "screen-size",
    name: L("Screen size", "حجم الشاشة"),
    type: "SELECT",
    group: "display",
    filterable: true,
    values: [sel("1-5", '1.5"'), sel("1-9", '1.9"'), sel("6-1", '6.1"'), sel("6-3", '6.3"'), sel("6-5", '6.5"'), sel("6-7", '6.7"'), sel("6-8", '6.8"'), sel("6-9", '6.9"'), sel("8-0", '8.0"'), sel("11", '11"'), sel("11-2", '11.2"'), sel("13", '13"'), sel("13-6", '13.6"'), sel("15", '15"')],
  },
  { key: "refresh-rate", name: L("Refresh rate", "معدل التحديث"), type: "SELECT", group: "display", filterable: true, values: [sel("60hz", "60Hz"), sel("90hz", "90Hz"), sel("120hz", "120Hz"), sel("144hz", "144Hz")] },
  { key: "panel", name: L("Panel", "نوع الشاشة"), type: "SELECT", group: "display", values: [sel("ltpo-oled", "LTPO OLED"), sel("amoled", "Dynamic AMOLED 2X"), sel("oled", "OLED"), sel("lcd", "Liquid Retina LCD"), sel("tandem-oled", "Tandem OLED")] },
  { key: "processor", name: L("Processor", "المعالج"), type: "TEXT", group: "performance" },
  {
    key: "os",
    name: L("Operating system", "نظام التشغيل"),
    type: "SELECT",
    group: "general",
    filterable: true,
    values: [sel("ios", "iOS"), sel("android", "Android", "أندرويد"), sel("ipados", "iPadOS"), sel("watchos", "watchOS"), sel("wearos", "Wear OS"), sel("harmonyos", "HarmonyOS"), sel("macos", "macOS"), sel("hyperos", "HyperOS")],
  },
  { key: "main-camera", name: L("Main camera", "الكاميرا الرئيسية"), type: "TEXT", group: "camera" },
  { key: "front-camera", name: L("Front camera", "الكاميرا الأمامية"), type: "TEXT", group: "camera" },
  { key: "video", name: L("Video", "الفيديو"), type: "TEXT", group: "camera" },
  { key: "battery", name: L("Battery", "البطارية"), type: "TEXT", group: "battery" },
  { key: "charging", name: L("Charging", "الشحن"), type: "TEXT", group: "battery" },
  { key: "network", name: L("Network", "الشبكة"), type: "SELECT", group: "connectivity", filterable: true, values: [sel("5g", "5G"), sel("4g", "4G LTE"), sel("wifi", "Wi-Fi only", "واي فاي فقط")] },
  { key: "nfc", name: L("NFC", "NFC"), type: "BOOLEAN", group: "connectivity" },
  {
    key: "connector",
    name: L("Connector", "المنفذ"),
    type: "SELECT",
    group: "connectivity",
    filterable: true,
    values: [sel("usb-c", "USB-C"), sel("lightning", "Lightning"), sel("magsafe", "MagSafe"), sel("qi2", "Qi2 wireless", "لاسلكي Qi2"), sel("bluetooth", "Bluetooth")],
  },
  { key: "wattage", name: L("Power output", "قدرة الشحن"), type: "SELECT", group: "battery", filterable: true, values: [sel("20w", "20W"), sel("25w", "25W"), sel("30w", "30W"), sel("45w", "45W"), sel("65w", "65W"), sel("100w", "100W"), sel("240w", "240W")] },
  {
    key: "compatibility",
    name: L("Compatible with", "متوافق مع"),
    type: "MULTISELECT",
    group: "general",
    filterable: true,
    values: [sel("iphone-17-pro", "iPhone 17 Pro"), sel("iphone-17", "iPhone 17"), sel("galaxy-s25-ultra", "Galaxy S25 Ultra"), sel("all-usb-c", "All USB-C devices", "جميع أجهزة USB-C"), sel("iphone", "iPhone"), sel("android", "Android", "أندرويد")],
  },
  { key: "material", name: L("Material", "الخامة"), type: "SELECT", group: "physical", filterable: true, values: [sel("silicone", "Silicone", "سيليكون"), sel("polycarbonate", "Clear polycarbonate", "بولي كربونات شفاف"), sel("aramid", "Aramid fibre", "ألياف الأراميد"), sel("braided", "Braided nylon", "نايلون مضفّر"), sel("aluminium", "Aluminium", "ألمنيوم"), sel("titanium", "Titanium", "تيتانيوم")] },
  { key: "anc", name: L("Active noise cancellation", "إلغاء الضوضاء النشط"), type: "BOOLEAN", group: "general", filterable: false },
  { key: "water-resistance", name: L("Water resistance", "مقاومة الماء"), type: "TEXT", group: "physical" },
  { key: "dimensions", name: L("Dimensions", "الأبعاد"), type: "TEXT", group: "physical" },
  { key: "weight", name: L("Weight", "الوزن"), type: "TEXT", group: "physical" },
  { key: "capacity", name: L("Capacity", "السعة"), type: "SELECT", group: "battery", filterable: true, values: [sel("5000mah", "5,000 mAh"), sel("10000mah", "10,000 mAh"), sel("20000mah", "20,000 mAh")] },
];

export type CategoryDef = { slug: string; name: L; description?: L; children?: CategoryDef[]; featured?: boolean; icon?: string; art?: { kind: DeviceKind; color: string; tint: [string, string] }; attributes?: string[] };

const phoneAttrs = ["color", "storage", "ram", "screen-size", "refresh-rate", "os", "network"];

export const CATEGORIES: CategoryDef[] = [
  {
    slug: "smartphones",
    name: L("Smartphones", "الهواتف الذكية"),
    description: L("The latest iPhone, Galaxy, Pixel, Xiaomi, OnePlus and Huawei phones — genuine, with local warranty.", "أحدث هواتف آيفون وجالكسي وبكسل وشاومي وون بلس وهواوي — أصلية مع كفالة محلية."),
    featured: true,
    icon: "Smartphone",
    art: { kind: "phone-pro", color: "#e46a2e", tint: ["#fff4ec", "#fde1cc"] },
    attributes: phoneAttrs,
    children: [
      { slug: "iphones", name: L("iPhone", "آيفون"), featured: true, art: { kind: "phone-pro", color: "#2c3e5c", tint: ["#eef2f8", "#d7dfec"] }, attributes: phoneAttrs },
      {
        slug: "android",
        name: L("Android phones", "هواتف أندرويد"),
        featured: true,
        art: { kind: "phone", color: "#3e6b55", tint: ["#eef6f0", "#d6e9dc"] },
        attributes: phoneAttrs,
        children: [
          {
            slug: "samsung-galaxy",
            name: L("Samsung Galaxy", "سامسونج جالكسي"),
            children: [
              { slug: "galaxy-s", name: L("Galaxy S series", "سلسلة جالكسي S") },
              { slug: "galaxy-z", name: L("Galaxy Z foldables", "جالكسي Z القابلة للطي") },
              { slug: "galaxy-a", name: L("Galaxy A series", "سلسلة جالكسي A") },
            ],
          },
          { slug: "google-pixel", name: L("Google Pixel", "جوجل بكسل") },
          { slug: "xiaomi-redmi", name: L("Xiaomi & Redmi", "شاومي وريدمي") },
          { slug: "oneplus-phones", name: L("OnePlus", "ون بلس") },
          { slug: "huawei-phones", name: L("Huawei", "هواوي") },
        ],
      },
    ],
  },
  {
    slug: "tablets",
    name: L("Tablets", "الأجهزة اللوحية"),
    description: L("iPad, Galaxy Tab and Xiaomi Pad for work, study and play.", "آيباد وجالكسي تاب وشاومي باد للعمل والدراسة والترفيه."),
    featured: true,
    icon: "Tablet",
    art: { kind: "tablet", color: "#9fb2c8", tint: ["#f0f4f9", "#dbe4ef"] },
    attributes: ["color", "storage", "screen-size", "os", "network"],
  },
  {
    slug: "laptops",
    name: L("Laptops", "اللابتوبات"),
    featured: true,
    icon: "Laptop",
    art: { kind: "laptop", color: "#d9dadc", tint: ["#f4f4f6", "#e1e2e7"] },
    attributes: ["color", "storage", "ram", "screen-size", "os"],
  },
  {
    slug: "wearables",
    name: L("Wearables", "الأجهزة القابلة للارتداء"),
    featured: true,
    icon: "Watch",
    art: { kind: "watch", color: "#2b2b2d", tint: ["#fff1f2", "#fbd5da"] },
    attributes: ["color", "os", "screen-size"],
    children: [
      { slug: "smart-watches", name: L("Smart watches", "الساعات الذكية") },
      { slug: "fitness-bands", name: L("Fitness bands", "أساور اللياقة") },
    ],
  },
  {
    slug: "audio",
    name: L("Audio", "الصوتيات"),
    featured: true,
    icon: "Headphones",
    art: { kind: "earbuds", color: "#f2f2f4", tint: ["#f5f3ff", "#e3defc"] },
    attributes: ["color", "connector"],
    children: [
      { slug: "earbuds", name: L("Earbuds", "سماعات لاسلكية") },
      { slug: "headphones", name: L("Headphones", "سماعات رأس") },
    ],
  },
  {
    slug: "accessories",
    name: L("Accessories", "الإكسسوارات"),
    featured: true,
    icon: "Cable",
    art: { kind: "charger", color: "#f2f2f4", tint: ["#ecfdf5", "#cdf3e1"] },
    children: [
      { slug: "chargers", name: L("Chargers", "الشواحن"), attributes: ["wattage", "connector"] },
      { slug: "power-banks", name: L("Power banks", "باور بانك"), attributes: ["capacity", "wattage", "connector"] },
      { slug: "cables", name: L("Cables", "الكوابل"), attributes: ["connector", "material", "wattage"] },
      {
        slug: "cases",
        name: L("Cases & protection", "الأغطية والحماية"),
        attributes: ["compatibility", "material", "color"],
        children: [{ slug: "iphone-cases", name: L("iPhone cases", "أغطية آيفون"), children: [{ slug: "iphone-17-pro-cases", name: L("iPhone 17 Pro cases", "أغطية آيفون 17 برو") }] }],
      },
    ],
  },
];

export const BRANDS = [
  { slug: "apple", name: L("Apple", "أبل"), color: "#111111", featured: true, description: L("iPhone, iPad, Mac, Apple Watch and AirPods — designed in California.", "آيفون وآيباد وماك وساعة أبل وإيربودز — مصممة في كاليفورنيا.") },
  { slug: "samsung", name: L("Samsung", "سامسونج"), color: "#1428a0", featured: true, description: L("Galaxy smartphones, tablets, wearables and more.", "هواتف وأجهزة لوحية وأجهزة قابلة للارتداء من جالكسي.") },
  { slug: "google", name: L("Google", "جوجل"), color: "#4285f4", featured: true, description: L("Pixel phones, watches and earbuds with Google AI.", "هواتف وساعات وسماعات بكسل مع ذكاء جوجل.") },
  { slug: "xiaomi", name: L("Xiaomi", "شاومي"), color: "#ff6900", featured: true, description: L("Flagship performance and excellent value.", "أداء رائد وقيمة ممتازة.") },
  { slug: "oneplus", name: L("OnePlus", "ون بلس"), color: "#eb0028", featured: true, description: L("Fast and smooth. Never settle.", "سريع وسلس.") },
  { slug: "huawei", name: L("Huawei", "هواوي"), color: "#cf0a2c", featured: true, description: L("Pura and nova phones, watches and wearables.", "هواتف بورا ونوفا والساعات والأجهزة القابلة للارتداء.") },
  { slug: "sony", name: L("Sony", "سوني"), color: "#000000", featured: false, description: L("Industry-leading noise-cancelling audio.", "صوتيات رائدة بتقنية إلغاء الضوضاء.") },
  { slug: "anker", name: L("Anker", "أنكر"), color: "#00a7e1", featured: true, description: L("Charging done right — GaN chargers, power banks and cables.", "شحن بالطريقة الصحيحة — شواحن GaN وباور بانك وكوابل.") },
];

type VariantAxis = { attr: "color" | "storage" | "ram"; values: string[] };

export type ProductDef = {
  slug: string;
  sku: string;
  name: L;
  brand: string;
  categories: string[]; // category slugs (first = primary)
  kind: DeviceKind;
  price: number;
  sale?: number;
  saleDays?: number;
  stock?: number;
  /** Price delta per option value (JOD), e.g. { "512gb": 150 } */
  priceDelta?: Record<string, number>;
  axes?: VariantAxis[];
  colors?: string[]; // for simple products: descriptive colour
  specs?: Record<string, string | string[] | boolean>;
  short: L;
  description?: L;
  flags?: { featured?: boolean; new?: boolean; bestSeller?: boolean; limited?: boolean };
  weight?: number;
  warranty?: L;
};

const W1 = L("1-year local warranty", "كفالة محلية لمدة سنة");
const W2 = L("2-year local warranty", "كفالة محلية لمدة سنتين");

export const PRODUCTS: ProductDef[] = [
  {
    slug: "iphone-17-pro",
    sku: "APL-IP17P",
    name: L("iPhone 17 Pro", "آيفون 17 برو"),
    brand: "apple",
    categories: ["iphones"],
    kind: "phone-pro",
    price: 949,
    axes: [
      { attr: "color", values: ["cosmic-orange", "deep-blue", "silver"] },
      { attr: "storage", values: ["256gb", "512gb", "1tb"] },
    ],
    priceDelta: { "512gb": 160, "1tb": 330 },
    specs: { "screen-size": "6-3", "refresh-rate": "120hz", panel: "ltpo-oled", processor: "A19 Pro", os: "ios", "main-camera": "48MP Fusion + 48MP Ultra Wide + 48MP 4× Telephoto", "front-camera": "18MP Center Stage", video: "4K 120fps Dolby Vision, ProRes RAW", battery: "Up to 31 hours video playback", charging: "40W wired (50% in 20 min), 25W MagSafe", network: "5g", nfc: true, connector: ["usb-c"], "water-resistance": "IP68", weight: "204 g" },
    short: L("Aluminium unibody, A19 Pro and the biggest leap in iPhone camera and battery yet.", "هيكل ألمنيوم موحّد ومعالج A19 Pro وأكبر قفزة في الكاميرا والبطارية في آيفون."),
    description: L(
      "<p>iPhone 17 Pro is built from a heat-forged aluminium unibody with a vapour chamber that keeps <strong>A19 Pro</strong> cool under sustained load — so games, 4K ProRes recording and on-device Apple Intelligence stay fast.</p><p>The Pro Fusion camera system brings three 48MP cameras, including a new 4× telephoto with up to 8× optical-quality zoom. Ceramic Shield 2 on the front is tougher than ever, and the 6.3\" ProMotion display goes up to 3000 nits outdoors.</p>",
      "<p>صُنع آيفون 17 برو من هيكل ألمنيوم موحّد مع غرفة تبخير تحافظ على برودة <strong>A19 Pro</strong> تحت الأحمال المستمرة — لتبقى الألعاب وتسجيل ProRes بدقة 4K وميزات Apple Intelligence سريعة.</p><p>يقدّم نظام كاميرات Pro Fusion ثلاث كاميرات بدقة 48 ميجابكسل، بما فيها عدسة تقريب جديدة 4× مع تقريب حتى 8× بجودة بصرية. وتأتي شاشة ProMotion بقياس 6.3 إنش بسطوع يصل إلى 3000 شمعة في الخارج.</p>",
    ),
    flags: { featured: true, new: true, bestSeller: true },
    weight: 204,
    warranty: W1,
  },
  {
    slug: "iphone-17",
    sku: "APL-IP17",
    name: L("iPhone 17", "آيفون 17"),
    brand: "apple",
    categories: ["iphones"],
    kind: "phone",
    price: 669,
    axes: [
      { attr: "color", values: ["black", "lavender", "sage", "mist-blue", "white"] },
      { attr: "storage", values: ["256gb", "512gb"] },
    ],
    priceDelta: { "512gb": 160 },
    specs: { "screen-size": "6-3", "refresh-rate": "120hz", panel: "oled", processor: "A19", os: "ios", "main-camera": "48MP Dual Fusion", "front-camera": "18MP Center Stage", video: "4K 60fps Dolby Vision", battery: "Up to 30 hours video playback", charging: "40W wired, 25W MagSafe", network: "5g", nfc: true, connector: ["usb-c"], "water-resistance": "IP68", weight: "177 g" },
    short: L("ProMotion comes to iPhone 17, with a brighter display and an 18MP Center Stage front camera.", "شاشة ProMotion في آيفون 17 مع سطوع أعلى وكاميرا أمامية 18 ميجابكسل."),
    flags: { featured: true, new: true },
    weight: 177,
    warranty: W1,
  },
  {
    slug: "iphone-air",
    sku: "APL-IPAIR",
    name: L("iPhone Air", "آيفون إير"),
    brand: "apple",
    categories: ["iphones"],
    kind: "phone",
    price: 829,
    sale: 779,
    saleDays: 10,
    axes: [
      { attr: "color", values: ["sky-blue", "starlight", "jet-black"] },
      { attr: "storage", values: ["256gb", "512gb", "1tb"] },
    ],
    priceDelta: { "512gb": 160, "1tb": 330 },
    specs: { "screen-size": "6-5", "refresh-rate": "120hz", panel: "oled", processor: "A19 Pro", os: "ios", "main-camera": "48MP Fusion", "front-camera": "18MP Center Stage", network: "5g", nfc: true, connector: ["usb-c"], weight: "165 g" },
    short: L("The thinnest iPhone ever at 5.6 mm, with pro performance inside.", "أنحف آيفون على الإطلاق بسماكة 5.6 مم مع أداء احترافي."),
    flags: { new: true },
    weight: 165,
    warranty: W1,
  },
  {
    slug: "galaxy-s25-ultra",
    sku: "SMS-S25U",
    name: L("Samsung Galaxy S25 Ultra", "سامسونج جالكسي S25 ألترا"),
    brand: "samsung",
    categories: ["galaxy-s"],
    kind: "phone-pro",
    price: 869,
    sale: 779,
    saleDays: 14,
    axes: [
      { attr: "color", values: ["titanium-black", "titanium-silverblue", "titanium-gray"] },
      { attr: "storage", values: ["256gb", "512gb", "1tb"] },
    ],
    priceDelta: { "512gb": 90, "1tb": 260 },
    specs: { "screen-size": "6-9", "refresh-rate": "120hz", panel: "amoled", processor: "Snapdragon 8 Elite for Galaxy", ram: "12gb", os: "android", "main-camera": "200MP + 50MP UW + 50MP 5× + 10MP 3×", "front-camera": "12MP", video: "8K 30fps", battery: "5000 mAh", charging: "45W wired, 15W wireless", network: "5g", nfc: true, connector: ["usb-c"], "water-resistance": "IP68", material: "titanium", weight: "218 g" },
    short: L("Titanium design, built-in S Pen, 200MP camera and Galaxy AI.", "تصميم من التيتانيوم وقلم S Pen مدمج وكاميرا 200 ميجابكسل وGalaxy AI."),
    description: L(
      "<p>The Galaxy S25 Ultra pairs a flat 6.9\" Dynamic AMOLED 2X display with anti-reflective Corning Gorilla Armor 2 and the fastest Snapdragon ever in a Galaxy.</p><ul><li>200MP wide camera with ProVisual Engine</li><li>Built-in S Pen for notes and precise editing</li><li>Seven years of OS and security updates</li></ul>",
      "<p>يجمع جالكسي S25 ألترا بين شاشة Dynamic AMOLED 2X مسطحة بقياس 6.9 إنش مع زجاج Gorilla Armor 2 المضاد للانعكاس وأسرع معالج Snapdragon في جالكسي.</p><ul><li>كاميرا عريضة 200 ميجابكسل مع ProVisual Engine</li><li>قلم S Pen مدمج للملاحظات والتحرير الدقيق</li><li>سبع سنوات من تحديثات النظام والأمان</li></ul>",
    ),
    flags: { featured: true, bestSeller: true },
    weight: 218,
    warranty: W1,
  },
  {
    slug: "galaxy-s25",
    sku: "SMS-S25",
    name: L("Samsung Galaxy S25", "سامسونج جالكسي S25"),
    brand: "samsung",
    categories: ["galaxy-s"],
    kind: "phone",
    price: 559,
    axes: [
      { attr: "color", values: ["navy", "icy-blue", "mint", "silver"] },
      { attr: "storage", values: ["128gb", "256gb"] },
    ],
    priceDelta: { "256gb": 50 },
    specs: { "screen-size": "6-1", "refresh-rate": "120hz", panel: "amoled", processor: "Snapdragon 8 Elite for Galaxy", ram: "12gb", os: "android", "main-camera": "50MP + 12MP UW + 10MP 3×", battery: "4000 mAh", charging: "25W wired", network: "5g", nfc: true, connector: ["usb-c"], weight: "162 g" },
    short: L("Compact flagship with Galaxy AI and a brilliant 120Hz display.", "هاتف رائد بحجم صغير مع Galaxy AI وشاشة 120 هرتز."),
    flags: { bestSeller: true },
    weight: 162,
    warranty: W1,
  },
  {
    slug: "galaxy-z-fold7",
    sku: "SMS-ZF7",
    name: L("Samsung Galaxy Z Fold7", "سامسونج جالكسي Z فولد 7"),
    brand: "samsung",
    categories: ["galaxy-z"],
    kind: "fold",
    price: 1299,
    axes: [
      { attr: "color", values: ["navy", "silver", "jet-black"] },
      { attr: "storage", values: ["256gb", "512gb"] },
    ],
    priceDelta: { "512gb": 120 },
    specs: { "screen-size": "8-0", "refresh-rate": "120hz", panel: "amoled", processor: "Snapdragon 8 Elite for Galaxy", ram: "12gb", os: "android", "main-camera": "200MP + 12MP UW + 10MP 3×", battery: "4400 mAh", network: "5g", nfc: true, connector: ["usb-c"], weight: "215 g" },
    short: L("The thinnest, lightest Galaxy Fold — a tablet in your pocket.", "أنحف وأخف جالكسي فولد — جهاز لوحي في جيبك."),
    flags: { new: true, limited: true },
    weight: 215,
    warranty: W1,
  },
  {
    slug: "galaxy-z-flip7",
    sku: "SMS-ZFL7",
    name: L("Samsung Galaxy Z Flip7", "سامسونج جالكسي Z فليب 7"),
    brand: "samsung",
    categories: ["galaxy-z"],
    kind: "flip",
    price: 739,
    sale: 689,
    saleDays: 7,
    axes: [{ attr: "color", values: ["jet-black", "deep-blue", "mint"] }, { attr: "storage", values: ["256gb", "512gb"] }],
    priceDelta: { "512gb": 80 },
    specs: { "screen-size": "6-9", "refresh-rate": "120hz", panel: "amoled", processor: "Exynos 2500", ram: "12gb", os: "android", "main-camera": "50MP + 12MP UW", battery: "4300 mAh", network: "5g", nfc: true, connector: ["usb-c"], weight: "188 g" },
    short: L("Edge-to-edge FlexWindow and a pocketable flip design.", "شاشة FlexWindow من الحافة إلى الحافة وتصميم قابل للطي."),
    weight: 188,
    warranty: W1,
  },
  {
    slug: "galaxy-a56-5g",
    sku: "SMS-A56",
    name: L("Samsung Galaxy A56 5G", "سامسونج جالكسي A56 5G"),
    brand: "samsung",
    categories: ["galaxy-a"],
    kind: "phone",
    price: 289,
    sale: 259,
    axes: [{ attr: "color", values: ["black", "pink", "mint"] }, { attr: "storage", values: ["128gb", "256gb"] }],
    priceDelta: { "256gb": 30 },
    specs: { "screen-size": "6-7", "refresh-rate": "120hz", panel: "amoled", processor: "Exynos 1580", ram: "8gb", os: "android", "main-camera": "50MP OIS + 12MP UW + 5MP", battery: "5000 mAh", charging: "45W wired", network: "5g", nfc: true, connector: ["usb-c"], "water-resistance": "IP67", weight: "198 g" },
    short: L("Awesome Intelligence, 6 years of updates and 45W fast charging.", "ذكاء مذهل وتحديثات لست سنوات وشحن سريع 45 واط."),
    flags: { bestSeller: true },
    weight: 198,
    warranty: W1,
  },
  {
    slug: "pixel-10-pro",
    sku: "GGL-P10P",
    name: L("Google Pixel 10 Pro", "جوجل بكسل 10 برو"),
    brand: "google",
    categories: ["google-pixel"],
    kind: "phone-pro",
    price: 799,
    axes: [{ attr: "color", values: ["obsidian", "porcelain", "moonstone"] }, { attr: "storage", values: ["128gb", "256gb", "512gb"] }],
    priceDelta: { "256gb": 70, "512gb": 180 },
    specs: { "screen-size": "6-3", "refresh-rate": "120hz", panel: "ltpo-oled", processor: "Google Tensor G5", ram: "16gb", os: "android", "main-camera": "50MP + 48MP UW + 48MP 5×", "front-camera": "42MP", battery: "4870 mAh", charging: "30W wired, Qi2 15W", network: "5g", nfc: true, connector: ["usb-c", "qi2"], "water-resistance": "IP68", weight: "207 g" },
    short: L("Tensor G5, 100× Pro Res Zoom and Magic Cue — the most helpful Pixel yet.", "معالج Tensor G5 وتقريب Pro Res حتى 100× وميزة Magic Cue."),
    flags: { featured: true, new: true },
    weight: 207,
    warranty: W1,
  },
  {
    slug: "pixel-10",
    sku: "GGL-P10",
    name: L("Google Pixel 10", "جوجل بكسل 10"),
    brand: "google",
    categories: ["google-pixel"],
    kind: "phone",
    price: 579,
    axes: [{ attr: "color", values: ["obsidian", "mist-blue", "lavender"] }, { attr: "storage", values: ["128gb", "256gb"] }],
    priceDelta: { "256gb": 70 },
    specs: { "screen-size": "6-3", "refresh-rate": "120hz", panel: "oled", processor: "Google Tensor G5", ram: "12gb", os: "android", "main-camera": "48MP + 13MP UW + 10.8MP 5×", battery: "4970 mAh", network: "5g", nfc: true, connector: ["usb-c"], weight: "204 g" },
    short: L("A telephoto camera on a non-Pro Pixel for the first time.", "عدسة تقريب لأول مرة في هاتف بكسل غير برو."),
    weight: 204,
    warranty: W1,
  },
  {
    slug: "xiaomi-15t-pro",
    sku: "XMI-15TP",
    name: L("Xiaomi 15T Pro", "شاومي 15T برو"),
    brand: "xiaomi",
    categories: ["xiaomi-redmi"],
    kind: "phone-pro",
    price: 529,
    sale: 489,
    axes: [{ attr: "color", values: ["black", "gold", "silver"] }, { attr: "storage", values: ["256gb", "512gb", "1tb"] }],
    priceDelta: { "512gb": 50, "1tb": 120 },
    specs: { "screen-size": "6-8", "refresh-rate": "144hz", panel: "amoled", processor: "MediaTek Dimensity 9400+", ram: "12gb", os: "hyperos", "main-camera": "Leica 50MP + 50MP 5× periscope + 12MP UW", battery: "5500 mAh", charging: "90W HyperCharge, 50W wireless", network: "5g", nfc: true, connector: ["usb-c"], weight: "210 g" },
    short: L("Leica optics with a 5× periscope and 90W HyperCharge.", "عدسات لايكا مع تقريب 5× وشحن HyperCharge بقدرة 90 واط."),
    flags: { featured: true },
    weight: 210,
    warranty: W1,
  },
  {
    slug: "redmi-note-14-pro-plus",
    sku: "XMI-RN14PP",
    name: L("Redmi Note 14 Pro+ 5G", "ريدمي نوت 14 برو+ 5G"),
    brand: "xiaomi",
    categories: ["xiaomi-redmi"],
    kind: "phone",
    price: 279,
    sale: 249,
    axes: [{ attr: "color", values: ["black", "purple", "sky-blue"] }, { attr: "ram", values: ["8gb", "12gb"] }],
    priceDelta: { "12gb": 30 },
    specs: { "screen-size": "6-7", "refresh-rate": "120hz", panel: "amoled", processor: "Snapdragon 7s Gen 3", storage: "256gb", os: "hyperos", "main-camera": "200MP OIS + 8MP UW + 2MP", battery: "5110 mAh", charging: "120W HyperCharge", network: "5g", nfc: true, connector: ["usb-c"], "water-resistance": "IP68", weight: "205 g" },
    short: L("200MP camera and 120W charging at a midrange price.", "كاميرا 200 ميجابكسل وشحن 120 واط بسعر متوسط."),
    flags: { bestSeller: true },
    weight: 205,
    warranty: W1,
  },
  {
    slug: "oneplus-13",
    sku: "OPL-13",
    name: L("OnePlus 13", "ون بلس 13"),
    brand: "oneplus",
    categories: ["oneplus-phones"],
    kind: "phone-pro",
    price: 649,
    axes: [{ attr: "color", values: ["black", "mist-blue"] }, { attr: "ram", values: ["12gb", "16gb"] }],
    priceDelta: { "16gb": 70 },
    specs: { "screen-size": "6-8", "refresh-rate": "120hz", panel: "ltpo-oled", processor: "Snapdragon 8 Elite", storage: "512gb", os: "android", "main-camera": "Hasselblad 50MP ×3", battery: "6000 mAh", charging: "100W SUPERVOOC, 50W wireless", network: "5g", nfc: true, connector: ["usb-c"], "water-resistance": "IP69", weight: "213 g" },
    short: L("Snapdragon 8 Elite, Hasselblad cameras and a 6000 mAh battery.", "معالج Snapdragon 8 Elite وكاميرات Hasselblad وبطارية 6000 ملي أمبير."),
    weight: 213,
    warranty: W1,
  },
  {
    slug: "huawei-pura-80-pro",
    sku: "HWI-P80P",
    name: L("Huawei Pura 80 Pro", "هواوي بورا 80 برو"),
    brand: "huawei",
    categories: ["huawei-phones"],
    kind: "phone-pro",
    price: 899,
    axes: [{ attr: "color", values: ["black", "gold"] }],
    stock: 9,
    specs: { "screen-size": "6-8", "refresh-rate": "120hz", panel: "ltpo-oled", processor: "Kirin 9020", ram: "12gb", storage: "512gb", os: "harmonyos", "main-camera": "XMAGE 50MP 1\" + 40MP UW + 48MP telephoto", battery: "5170 mAh", charging: "100W wired, 80W wireless", network: "5g", nfc: true, connector: ["usb-c"], weight: "214 g" },
    short: L("A 1-inch class XMAGE camera with ultra-lighting telephoto.", "كاميرا XMAGE بمستشعر بقياس إنش واحد."),
    flags: { limited: true },
    weight: 214,
    warranty: W1,
  },
  // Tablets
  {
    slug: "ipad-pro-11-m5",
    sku: "APL-IPP11M5",
    name: L('iPad Pro 11" (M5)', 'آيباد برو 11 إنش (M5)'),
    brand: "apple",
    categories: ["tablets"],
    kind: "tablet",
    price: 849,
    axes: [{ attr: "color", values: ["silver", "black"] }, { attr: "storage", values: ["256gb", "512gb", "1tb"] }],
    priceDelta: { "512gb": 160, "1tb": 400 },
    specs: { "screen-size": "11", "refresh-rate": "120hz", panel: "tandem-oled", processor: "Apple M5", os: "ipados", network: "wifi", connector: ["usb-c"], weight: "444 g" },
    short: L("Ultra Retina XDR tandem OLED and the M5 chip.", "شاشة Ultra Retina XDR وشريحة M5."),
    flags: { featured: true, new: true },
    weight: 444,
    warranty: W1,
  },
  {
    slug: "ipad-air-m3",
    sku: "APL-IPAM3",
    name: L('iPad Air 11" (M3)', 'آيباد إير 11 إنش (M3)'),
    brand: "apple",
    categories: ["tablets"],
    kind: "tablet",
    price: 499,
    sale: 459,
    axes: [{ attr: "color", values: ["sky-blue", "purple", "starlight", "black"] }, { attr: "storage", values: ["128gb", "256gb"] }],
    priceDelta: { "256gb": 80 },
    specs: { "screen-size": "11", panel: "lcd", processor: "Apple M3", os: "ipados", network: "wifi", connector: ["usb-c"] },
    short: L("M3 power in a thin, light design.", "قوة M3 في تصميم نحيف وخفيف."),
    weight: 460,
    warranty: W1,
  },
  {
    slug: "galaxy-tab-s10-fe",
    sku: "SMS-TS10FE",
    name: L("Samsung Galaxy Tab S10 FE", "سامسونج جالكسي تاب S10 FE"),
    brand: "samsung",
    categories: ["tablets"],
    kind: "tablet",
    price: 349,
    axes: [{ attr: "color", values: ["silver", "titanium-gray", "sky-blue"] }],
    specs: { "screen-size": "11", "refresh-rate": "90hz", panel: "lcd", processor: "Exynos 1580", ram: "8gb", storage: "128gb", os: "android", network: "wifi", connector: ["usb-c"], "water-resistance": "IP68" },
    short: L("S Pen in the box and IP68 — a tablet built for real life.", "قلم S Pen مرفق ومقاومة IP68."),
    weight: 497,
    warranty: W1,
  },
  {
    slug: "xiaomi-pad-7",
    sku: "XMI-PAD7",
    name: L("Xiaomi Pad 7", "شاومي باد 7"),
    brand: "xiaomi",
    categories: ["tablets"],
    kind: "tablet",
    price: 289,
    axes: [{ attr: "color", values: ["sage", "black", "sky-blue"] }, { attr: "storage", values: ["128gb", "256gb"] }],
    priceDelta: { "256gb": 30 },
    specs: { "screen-size": "11-2", "refresh-rate": "144hz", panel: "lcd", processor: "Snapdragon 7+ Gen 3", ram: "8gb", os: "hyperos", network: "wifi", connector: ["usb-c"] },
    short: L("3.2K 144Hz display with a crisp, paper-like matte option.", "شاشة 3.2K بمعدل 144 هرتز."),
    weight: 500,
    warranty: W1,
  },
  // Laptops
  {
    slug: "macbook-air-13-m4",
    sku: "APL-MBA13M4",
    name: L('MacBook Air 13" (M4)', 'ماك بوك إير 13 إنش (M4)'),
    brand: "apple",
    categories: ["laptops"],
    kind: "laptop",
    price: 799,
    axes: [{ attr: "color", values: ["sky-blue", "silver", "starlight", "black"] }, { attr: "storage", values: ["256gb", "512gb"] }],
    priceDelta: { "512gb": 160 },
    specs: { "screen-size": "13-6", processor: "Apple M4", ram: "16gb", os: "macos", connector: ["usb-c", "magsafe"], battery: "Up to 18 hours", weight: "1.24 kg" },
    short: L("M4, 16GB unified memory and all-day battery in a fanless design.", "شريحة M4 وذاكرة 16 جيجابايت وبطارية تدوم طوال اليوم."),
    flags: { featured: true, bestSeller: true },
    weight: 1240,
    warranty: W1,
  },
  // Wearables
  {
    slug: "apple-watch-series-11",
    sku: "APL-AWS11",
    name: L("Apple Watch Series 11", "ساعة أبل الإصدار 11"),
    brand: "apple",
    categories: ["smart-watches"],
    kind: "watch",
    price: 339,
    axes: [{ attr: "color", values: ["jet-black", "rose-gold", "silver"] }],
    specs: { "screen-size": "1-9", processor: "S10 SiP", os: "watchos", "water-resistance": "WR50, IP6X", battery: "Up to 24 hours" },
    short: L("Hypertension notifications, sleep score and 5G.", "إشعارات ارتفاع ضغط الدم ومؤشر النوم و5G."),
    flags: { new: true, featured: true },
    weight: 38,
    warranty: W1,
  },
  {
    slug: "galaxy-watch8",
    sku: "SMS-GW8",
    name: L("Samsung Galaxy Watch8", "سامسونج جالكسي ووتش 8"),
    brand: "samsung",
    categories: ["smart-watches"],
    kind: "watch",
    price: 259,
    sale: 229,
    axes: [{ attr: "color", values: ["silver", "titanium-gray"] }],
    specs: { "screen-size": "1-5", os: "wearos", "water-resistance": "5ATM, IP68", battery: "Up to 40 hours" },
    short: L("Antioxidant index, bedtime guidance and Gemini on your wrist.", "مؤشر مضادات الأكسدة وإرشادات النوم وGemini على معصمك."),
    weight: 30,
    warranty: W1,
  },
  {
    slug: "pixel-watch-4",
    sku: "GGL-PW4",
    name: L("Google Pixel Watch 4", "جوجل بكسل ووتش 4"),
    brand: "google",
    categories: ["smart-watches"],
    kind: "watch",
    price: 299,
    axes: [{ attr: "color", values: ["obsidian", "porcelain", "moonstone"] }],
    specs: { os: "wearos", "water-resistance": "5ATM, IP68", battery: "Up to 30 hours" },
    short: L("Domed Actua display and Fitbit health tracking.", "شاشة Actua مقببة وتتبع صحي من Fitbit."),
    weight: 31,
    warranty: W1,
  },
  {
    slug: "huawei-watch-gt-6",
    sku: "HWI-GT6",
    name: L("Huawei Watch GT 6", "هواوي ووتش GT 6"),
    brand: "huawei",
    categories: ["smart-watches"],
    kind: "watch",
    price: 189,
    axes: [{ attr: "color", values: ["black", "green"] }],
    specs: { os: "harmonyos", battery: "Up to 21 days", "water-resistance": "5ATM" },
    short: L("Up to 21 days of battery with precise cycling power metrics.", "بطارية تدوم حتى 21 يوماً."),
    weight: 44,
    warranty: W1,
  },
  {
    slug: "xiaomi-smart-band-10",
    sku: "XMI-SB10",
    name: L("Xiaomi Smart Band 10", "شاومي سمارت باند 10"),
    brand: "xiaomi",
    categories: ["fitness-bands"],
    kind: "band",
    price: 39,
    axes: [{ attr: "color", values: ["black", "pink", "mint"] }],
    specs: { battery: "Up to 21 days", "water-resistance": "5ATM" },
    short: L("A bright 1.72\" AMOLED and three weeks of battery.", "شاشة AMOLED ساطعة وبطارية لثلاثة أسابيع."),
    flags: { bestSeller: true },
    weight: 16,
    warranty: W1,
  },
  // Audio
  {
    slug: "airpods-pro-3",
    sku: "APL-APP3",
    name: L("AirPods Pro 3", "إيربودز برو 3"),
    brand: "apple",
    categories: ["earbuds"],
    kind: "earbuds",
    price: 209,
    colors: ["white"],
    specs: { anc: true, connector: ["usb-c", "bluetooth"], battery: "Up to 8 hours (ANC)", "water-resistance": "IP57" },
    short: L("World-class ANC, heart-rate sensing and Live Translation.", "إلغاء ضوضاء عالمي المستوى واستشعار معدل ضربات القلب."),
    flags: { featured: true, bestSeller: true, new: true },
    stock: 48,
    weight: 50,
    warranty: W1,
  },
  {
    slug: "airpods-4-anc",
    sku: "APL-AP4ANC",
    name: L("AirPods 4 with Active Noise Cancellation", "إيربودز 4 مع إلغاء الضوضاء النشط"),
    brand: "apple",
    categories: ["earbuds"],
    kind: "earbuds",
    price: 149,
    sale: 135,
    colors: ["white"],
    specs: { anc: true, connector: ["usb-c", "bluetooth"] },
    short: L("Open-ear comfort with ANC.", "راحة التصميم المفتوح مع إلغاء الضوضاء."),
    stock: 4,
    weight: 45,
    warranty: W1,
  },
  {
    slug: "galaxy-buds3-pro",
    sku: "SMS-GB3P",
    name: L("Samsung Galaxy Buds3 Pro", "سامسونج جالكسي بادز 3 برو"),
    brand: "samsung",
    categories: ["earbuds"],
    kind: "earbuds",
    price: 169,
    sale: 139,
    axes: [{ attr: "color", values: ["silver", "white"] }],
    specs: { anc: true, connector: ["usb-c", "bluetooth"], "water-resistance": "IP57" },
    short: L("Adaptive ANC and 24-bit Hi-Fi sound.", "إلغاء ضوضاء تكيّفي وصوت Hi-Fi بدقة 24 بت."),
    weight: 47,
    warranty: W1,
  },
  {
    slug: "sony-wh-1000xm6",
    sku: "SNY-XM6",
    name: L("Sony WH-1000XM6", "سوني WH-1000XM6"),
    brand: "sony",
    categories: ["headphones"],
    kind: "headphones",
    price: 329,
    axes: [{ attr: "color", values: ["black", "silver", "mist-blue"] }],
    specs: { anc: true, connector: ["usb-c", "bluetooth"], battery: "Up to 30 hours (ANC)" },
    short: L("Sony's best noise cancelling with a new 12-mic system.", "أفضل إلغاء ضوضاء من سوني مع نظام 12 ميكروفون."),
    flags: { featured: true },
    weight: 254,
    warranty: W2,
  },
  {
    slug: "pixel-buds-pro-2",
    sku: "GGL-PBP2",
    name: L("Google Pixel Buds Pro 2", "جوجل بكسل بادز برو 2"),
    brand: "google",
    categories: ["earbuds"],
    kind: "earbuds",
    price: 179,
    axes: [{ attr: "color", values: ["porcelain", "moonstone", "obsidian"] }],
    specs: { anc: true, connector: ["usb-c", "bluetooth"] },
    short: L("Tensor A1 chip with Silent Seal 2.0 ANC.", "شريحة Tensor A1 مع إلغاء ضوضاء Silent Seal 2.0."),
    weight: 62,
    warranty: W1,
  },
  // Accessories
  {
    slug: "apple-20w-usb-c-power-adapter",
    sku: "APL-20W",
    name: L("Apple 20W USB-C Power Adapter", "محوّل طاقة أبل USB-C بقدرة 20 واط"),
    brand: "apple",
    categories: ["chargers"],
    kind: "charger",
    price: 19,
    colors: ["white"],
    specs: { wattage: "20w", connector: ["usb-c"] },
    short: L("Fast, efficient charging at home, in the office or on the go.", "شحن سريع وفعّال في المنزل أو المكتب أو أثناء التنقل."),
    flags: { bestSeller: true },
    stock: 120,
    weight: 60,
    warranty: W1,
  },
  {
    slug: "samsung-45w-power-adapter",
    sku: "SMS-45W",
    name: L("Samsung 45W Power Adapter", "شاحن سامسونج 45 واط"),
    brand: "samsung",
    categories: ["chargers"],
    kind: "charger",
    price: 29,
    sale: 24,
    colors: ["black"],
    specs: { wattage: "45w", connector: ["usb-c"] },
    short: L("Super Fast Charging 2.0 for Galaxy S and Tab.", "شحن فائق السرعة 2.0 لأجهزة جالكسي."),
    stock: 60,
    weight: 70,
    warranty: W1,
  },
  {
    slug: "anker-nano-65w-gan",
    sku: "ANK-N65",
    name: L("Anker Nano Charger 65W (GaN)", "شاحن أنكر نانو 65 واط (GaN)"),
    brand: "anker",
    categories: ["chargers"],
    kind: "charger",
    price: 35,
    axes: [{ attr: "color", values: ["black", "white"] }],
    specs: { wattage: "65w", connector: ["usb-c"] },
    short: L("Charge a laptop and phone at once from a tiny GaN brick.", "اشحن لابتوب وهاتف معاً من شاحن GaN صغير."),
    flags: { bestSeller: true },
    weight: 112,
    warranty: W2,
  },
  {
    slug: "anker-maggo-power-bank-10k",
    sku: "ANK-MGO10K",
    name: L("Anker MagGo Power Bank (10K, Qi2)", "باور بانك أنكر MagGo (10000، Qi2)"),
    brand: "anker",
    categories: ["power-banks"],
    kind: "powerbank",
    price: 59,
    sale: 49,
    axes: [{ attr: "color", values: ["black", "white", "lavender"] }],
    specs: { capacity: "10000mah", wattage: "30w", connector: ["usb-c", "qi2"] },
    short: L("15W Qi2 magnetic charging with a smart display.", "شحن مغناطيسي Qi2 بقدرة 15 واط مع شاشة ذكية."),
    weight: 218,
    warranty: W2,
  },
  {
    slug: "anker-usb-c-cable-240w",
    sku: "ANK-C240",
    name: L("Anker USB-C to USB-C Cable 240W (1.8 m)", "كابل أنكر USB-C إلى USB-C بقدرة 240 واط (1.8 م)"),
    brand: "anker",
    categories: ["cables"],
    kind: "cable",
    price: 12,
    axes: [{ attr: "color", values: ["black", "white", "purple"] }],
    specs: { wattage: "240w", connector: ["usb-c"], material: "braided" },
    short: L("Braided, durable and fast enough for any laptop.", "مضفّر ومتين وسريع بما يكفي لأي لابتوب."),
    stock: 200,
    weight: 40,
    warranty: W2,
  },
  {
    slug: "iphone-17-pro-silicone-case-magsafe",
    sku: "APL-C17PSIL",
    name: L("iPhone 17 Pro Silicone Case with MagSafe", "غطاء سيليكون لآيفون 17 برو مع MagSafe"),
    brand: "apple",
    categories: ["iphone-17-pro-cases"],
    kind: "case",
    price: 49,
    axes: [{ attr: "color", values: ["black", "cosmic-orange", "deep-blue", "sage"] }],
    specs: { compatibility: ["iphone-17-pro"], material: "silicone", connector: ["magsafe"] },
    short: L("Soft-touch silicone with a microfibre lining.", "سيليكون ناعم الملمس مع بطانة من الألياف الدقيقة."),
    weight: 30,
    warranty: W1,
  },
  {
    slug: "galaxy-s25-ultra-clear-case",
    sku: "SMS-CS25UCL",
    name: L("Galaxy S25 Ultra Clear Case", "غطاء شفاف لجالكسي S25 ألترا"),
    brand: "samsung",
    categories: ["cases"],
    kind: "case",
    price: 19,
    colors: ["clear"],
    specs: { compatibility: ["galaxy-s25-ultra"], material: "polycarbonate" },
    short: L("Slim, scratch-resistant and shows off the titanium.", "رفيع ومقاوم للخدوش ويُظهر التيتانيوم."),
    stock: 3,
    weight: 25,
    warranty: W1,
  },
];

export const L_ = L;
